# Generated by Django 5.2 on 2025-08-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theschool', '0002_platformconfig_user_phone_number_feerecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportstaff',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supportstaff',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
        migrations.AddField(
            model_name='supportstaff',
            name='working_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='ClassRoom',
        ),
    ]
